spring:
  h2:
    console.enabled: true
  hibernate:
    ddl-auto: true
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql=true:logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        BasicBinder: TRACE




